# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/website-sphinx-app-docs.yml

variables:
    EPUB_NAME: KritaManual
    WEBSITE_LANGUAGES: en de fr nl uk_UA zh_CN ca pt_PT ko ja pl it sl tr
